language: node_js
node_js:
  - "6"
dist: trusty
sudo: false
install:
  - npm install
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
before_script:
    - npm run coverage
script:
  - npm run test
